#pragma once

typedef enum e_state_code {
    NONE,

    CONNECTION_REFUSED,

    SUCCESSFULLY_READ,
    SUCCESSFUL_REGISTRATION,
    SUCCESSFUL_LOGIN,
    USER_SUCCESSFULLY_ADDED_TO_CHAT,
    TEXT_MESSAGE_SENT_SUCCESSFULLY,
    USER_REMOVED_FROM_CHAT_SUCCESSFULLY,

    SUCH_LOGIN_ALREADY_EXISTS,
    SUCH_LOGIN_DOES_NOT_EXIST,
    WRONG_PASSWORD,
    SUCH_USER_IS_ALREADY_IN_CHAT
} t_state_code;
